server:
  port: 8080

log:
  destination: 127.0.0.1

logging:
  config: classpath:logback-dev.xml
  level:
    org.hibernate: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event
    username: event_user
    password: pa55w0rd
