server:
  port: 8080

log:
  destination: 127.0.0.1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event
    username: event_user
    password: pa55w0rd
  rabbitmq:
    host: 127.0.0.1
    username: rabbit
    password: qwesda
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
